### PR TITLE
Added emoji and changed logo

### PR DESCRIPTION
**Pull request by alenrajsp**
I've changed the logo (open to suggestions) and added emoji to the categories.

### CODE REVIEW

**Comment by firefly-cpp** [comment]
@alenrajsp, please do not change logo. Current logo is nice.

**Comment by alenrajsp** [comment]
Okay. Without logo. :)

**Comment by alenrajsp** [comment]
@firefly-cpp

**Comment by firefly-cpp** [comment]
Thanks.

**Pull request merged**
